/// A plugin loader using the [`libloading`](https://github.com/nagisa/rust_libloading) crate.
pub mod dylib;

/// Error generated by a plugin loader.
#[derive(Debug)]
pub enum PluginLoaderError {
    /// Error generated during plugin loading.
    Loading(String),
}

/// A trait to implement an object that load and stores plugins in memory.
pub trait PluginLoader {
    /// Load a plugin from a path and return a reference to it.
    fn load(
        &mut self,
        path: impl AsRef<std::path::Path>,
        engine: &mut rhai::Engine,
    ) -> Result<(), PluginLoaderError>;
}
